### ISSUE TITLE
Not possible to publish description in POM.XML

### ISSUE THREAD

**Issue by Nirvanchik** [wupdigital/android-maven-publish#28] opened 2018-10-13 20:20 UTC
I use Gradle 4.5 and digital.wup:android-maven-publish:3.3.0

When I add description, it  doesn't work. (It worked earlier, when we didn't use digital.wup plugin).
```
publishing {
    publications {
        mavenCustom(MavenPublication) {
            groupId 'com.our.lib'
            artifactId calculateArtifact(project)
            artifact sourceJar
            version libVersion

            from components.android
            pom.withXml {
                asNode().appendNode('description', "Built on commit: ")
            }
        }
    }
}
```

In resulting pom.xmls there is no description :-(

**Comment by warnyul** [comment] 2018-10-13 20:42
I can't reproduce this. It writes description tag at the end of pom file.

**Comment by Nirvanchik** [comment] 2018-10-15 08:03
It was mistake.

Our project is complicated and misconfigured. I added  "pom.withXml" in the wrong place. Sorry. 

You may close the issue.

**Comment by warnyul** [comment] 2018-10-15 08:05
Thanks for the feedback. I close the issue.

**Closed by warnyul** 2018-10-15 08:05 UTC
